[package]
name = "serde_integration"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository.workspace = true

[dependencies]
sellershut-core = { workspace = true, features = ["categories", "serde"] }
serde_json.workspace = true
