services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.9
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
    ports:
      - "7700:7700"
    networks:
      - sellershut
    volumes:
      - meili_data:/meili_data
    restart: unless-stopped

  categories-db:
    image: postgres:16.3
    restart: always
    # hostname: postgreshost
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - sellershut
    volumes:
      - postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3


networks:
  sellershut:

volumes:
  postgres:
  meili_data:
