[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.dev-categories]
command = "cargo"
args = [ "watch", "-c", "-x", "run --bin sellershut-api-categories" ]

[tasks.migrate]
dependencies = [
  { name = "migrate", path = "./crates/api-categories/Makefile.toml" },
  { name = "migrate", path = "./crates/api-users/Makefile.toml" }
]

[tasks.check]
install_crate = { crate_name = "cargo-hack", binary = "cargo", test_arg = ["hack", "--help"] }
dependencies = ["migrate"]
command = "cargo"
args = [ "hack", "--feature-powerset", "check" ]

[tasks.doc]
toolchain = "nightly"
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
dependencies = ["migrate"]
command = "cargo"
args = ["doc", "--all-features", "--no-deps"]
