[package]
name = "api-categories"
version = "0.1.0"
edition = "2021"
publish = false
license.workspace = true

[dependencies]
anyhow.workspace = true
core-services = { workspace = true, features = ["nats", "postgres", "rt-tokio", "telemetry"] }
dotenvy.workspace = true
sellershut-core = { workspace = true, features = ["categories", "serde"] }
sqlx = { workspace = true, features = ["macros", "migrate", "postgres", "runtime-tokio", "tls-rustls"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing.workspace = true
