[package]
name = "api-categories"
version = "0.1.0"
edition = "2021"
publish = false
license.workspace = true

[dependencies]
sellershut-core = { workspace = true, features = ["categories", "serde"] }
