[tasks.migrate]
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help" }
command = "sqlx"
args = [ "migrate", "run" ]
env_files = [
  ".env",
]

[tasks.dev]
command = "cargo"
args = [ "watch", "-c", "-x", "run --bin sellershut-api-categories" ]
