[package]
name = "sellershut-core"
version = "0.1.0"
edition = "2021"

[dependencies]
prost.workspace = true
prost-types = "0.13.1"
tonic.workspace = true

[build-dependencies]
tonic-build = "0.12.1"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
